// Este archivo contiene datos de PRUEBA (falsos) para poder ver
// el diseño del Marketplace funcionando, antes de conectar el backend real.
// Cuando el backend PHP esté listo, este archivo dejará de usarse.

import { Algoritmo } from '../../modelos/algoritmo.model';

export const ALGORITMOS_MOCK: Algoritmo[] = [
    {
        id: 1,
        nombre: 'Quantum FX Alpha',
        subtitulo: 'EUR/USD Scalper',
        descripcion:
            'High-frequency EUR/USD scalping with quantum-inspired optimization. Adaptive risk management con ajuste de volatilidad en tiempo real.',
        categoria: 'Forex',
        plataforma: 'MT5',
        verificado: true,
        rendimientoAnual: 127.4,
        sharpeRatio: 2.14,
        maxDrawdown: 8.2,
        winRate: 71.3,
        desarrollador: 'AlgoQuant Labs',
        rating: 4.8,
        numeroReviews: 47,
        numeroSuscriptores: 312,
        tags: ['SCALPING', 'HIGH-FREQ'],
        precioMensual: 49,
        historialRendimiento: [100, 104, 102, 108, 112, 110, 118, 124, 121, 127],
    },
    {
        id: 2,
        nombre: 'Neural Scalper X',
        subtitulo: 'AI-Powered FX',
        descripcion:
            'Scalper de deep learning entrenado en 10+ años de tick data. Señales LSTM con módulo de gestión de riesgo por reinforcement learning.',
        categoria: 'Forex',
        plataforma: 'LEAN',
        verificado: true,
        rendimientoAnual: 112.3,
        sharpeRatio: 1.76,
        maxDrawdown: 16.8,
        winRate: 66.9,
        desarrollador: 'NeuralAlpha AI',
        rating: 4.5,
        numeroReviews: 63,
        numeroSuscriptores: 421,
        tags: ['AI', 'DEEP LEARNING'],
        precioMensual: 69,
        historialRendimiento: [100, 103, 101, 106, 109, 105, 111, 115, 112, 112],
    },
    {
        id: 3,
        nombre: 'Crypto Momentum Pro',
        subtitulo: 'Multi-Coin Trend',
        descripcion:
            'Trend-following en BTC, ETH y top-10 altcoins. Momentum scoring con position sizing dinámico y rebalanceo automático.',
        categoria: 'Crypto',
        plataforma: 'LEAN',
        verificado: true,
        rendimientoAnual: 89.2,
        sharpeRatio: 1.87,
        maxDrawdown: 14.6,
        winRate: 64.8,
        desarrollador: 'CryptoSystems Dev',
        rating: 4.6,
        numeroReviews: 38,
        numeroSuscriptores: 245,
        tags: ['CRYPTO', 'TREND'],
        precioMensual: 39,
        historialRendimiento: [100, 102, 99, 106, 110, 107, 113, 117, 114, 118],
    },
    {
        id: 4,
        nombre: 'Equity Trend Follower',
        subtitulo: 'US Stocks & ETFs',
        descripcion:
            'Trend following sistemático en acciones US y ETFs sectoriales. Detección de breakouts con confirmación multi-timeframe.',
        categoria: 'Equities',
        plataforma: 'LEAN',
        verificado: true,
        rendimientoAnual: 73.6,
        sharpeRatio: 1.94,
        maxDrawdown: 11.3,
        winRate: 59.4,
        desarrollador: 'Systematic Edge',
        rating: 4.7,
        numeroReviews: 51,
        numeroSuscriptores: 278,
        tags: ['EQUITIES', 'ETFS'],
        precioMensual: 44,
        historialRendimiento: [100, 103, 105, 104, 109, 112, 110, 115, 116, 117],
    },
    {
        id: 5,
        nombre: 'Volatility Arbitrage',
        subtitulo: 'Multi-Asset Vol',
        descripcion:
            'Arbitraje estadístico explotando volatilidad implícita vs realizada. Pairs trading con exposición delta-neutral.',
        categoria: 'Options',
        plataforma: 'MT5',
        verificado: true,
        rendimientoAnual: 61.8,
        sharpeRatio: 2.31,
        maxDrawdown: 6.4,
        winRate: 73.1,
        desarrollador: 'QuantVol Research',
        rating: 4.9,
        numeroReviews: 29,
        numeroSuscriptores: 134,
        tags: ['OPTIONS', 'ARBITRAGE'],
        precioMensual: 59,
        historialRendimiento: [100, 101, 103, 102, 106, 108, 107, 110, 112, 113],
    },
    {
        id: 6,
        nombre: 'FX Carry Trade Pro',
        subtitulo: 'G10 Currency Pairs',
        descripcion:
            'Estrategia de carry trade optimizada en G10 con gestión de riesgo dinámica. Captura diferencial de tasas con exposición controlada.',
        categoria: 'Forex',
        plataforma: 'cTrader',
        verificado: false,
        rendimientoAnual: 52.4,
        sharpeRatio: 1.63,
        maxDrawdown: 9.7,
        winRate: 62.8,
        desarrollador: 'ForexPro Systems',
        rating: 4.2,
        numeroReviews: 31,
        numeroSuscriptores: 156,
        tags: ['CARRY', 'G10'],
        precioMensual: 35,
        historialRendimiento: [100, 101, 100, 103, 105, 104, 107, 109, 108, 110],
    },
    {
        id: 7,
        nombre: 'Gold Hedge System',
        subtitulo: 'XAU/USD Protection',
        descripcion:
            'Mean-reversion en XAUUSD con cobertura inteligente. Diseñado para ganancias consistentes con control estricto de drawdown.',
        categoria: 'Commodities',
        plataforma: 'MT5',
        verificado: false,
        rendimientoAnual: 45.1,
        sharpeRatio: 1.52,
        maxDrawdown: 5.8,
        winRate: 68.2,
        desarrollador: 'GoldPath Trading',
        rating: 4.3,
        numeroReviews: 22,
        numeroSuscriptores: 189,
        tags: ['GOLD', 'HEDGE'],
        precioMensual: 29,
        historialRendimiento: [100, 101, 102, 101, 104, 106, 105, 107, 108, 109],
    },
    {
        id: 8,
        nombre: 'Mean Rev Bonds',
        subtitulo: 'Fixed Income',
        descripcion:
            'Reversión a la media en bonos del Tesoro y spreads corporativos. Excelente correlación inversa con acciones para diversificación.',
        categoria: 'Equities',
        plataforma: 'LEAN',
        verificado: true,
        rendimientoAnual: 38.7,
        sharpeRatio: 2.05,
        maxDrawdown: 4.1,
        winRate: 76.2,
        desarrollador: 'BondAlgo Capital',
        rating: 4.7,
        numeroReviews: 18,
        numeroSuscriptores: 97,
        tags: ['BONDS', 'MEAN-REV'],
        precioMensual: 34,
        historialRendimiento: [100, 100, 101, 102, 101, 103, 104, 103, 105, 106],
    },
];